"""initial

Revision ID: 0a87f7da37bd
Revises: 
Create Date: 2026-04-20 21:17:31.699514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a87f7da37bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rating_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PERFORMANCE', 'TEAMWORK', 'INITIATIVE', 'QUALITY', 'LEADERSHIP', name='ratingcategory'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rating_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category', sa.Enum('PERFORMANCE', 'TEAMWORK', 'INITIATIVE', 'QUALITY', 'LEADERSHIP', name='ratingcategory'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['rating_metrics.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rating_employee_period', 'rating_entries', ['employee_id', 'period'], unique=False)
    op.create_index('ix_rating_period', 'rating_entries', ['period'], unique=False)
    op.create_table('rating_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('department_rank', sa.Integer(), nullable=False),
    sa.Column('percentile', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delta_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('delta_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_employee_period', 'rating_snapshots', ['employee_id', 'period'], unique=True)
    op.create_index('ix_snapshot_period_rank', 'rating_snapshots', ['period', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_period_rank', table_name='rating_snapshots')
    op.drop_index('ix_snapshot_employee_period', table_name='rating_snapshots')
    op.drop_table('rating_snapshots')
    op.drop_index('ix_rating_period', table_name='rating_entries')
    op.drop_index('ix_rating_employee_period', table_name='rating_entries')
    op.drop_table('rating_entries')
    op.drop_table('employees')
    op.drop_table('rating_metrics')
    op.drop_table('departments')
    # ### end Alembic commands ###

